positive_labels = [
    "an outstanding picture",
    "a beautiful wallpaper",
    "a stunning masterpiece",
    "a captivating image",
    "a breathtaking view",
    "a mesmerizing scene",
    "an awe-inspiring shot",
    "a vibrant photo",
    "a picturesque landscape",
    "an exquisite portrait",
    "a dazzling sunset",
    "a charming composition",
    "an elegant snapshot",
    "a delightful frame",
    "a radiant display",
    "an enchanting moment",
    "a sublime capture",
    "a magnificent photograph",
    "a glorious scenery",
    "an impressive artwork",
    "a lovely panorama",
    "an exceptional creation",
    "a striking perspective",
    "a graceful depiction",
    "an appealing vision",
    "a brilliant exposure",
    "a remarkable sight",
    "a marvelous vista",
    "a splendid illustration",
    "an illustrious view",
    "a perfect photograph",
    "a tasteful arrangement",
    "a harmonious picture",
    "a beautiful snapshot",
    "a vibrant masterpiece",
    "an iconic capture",
    "a refined image",
    "an attractive wallpaper",
    "a polished photograph",
    "a memorable shot",
    "a scenic vista",
    "a colorful display",
    "an artistic composition",
    "a soothing image",
    "a breathtaking landscape",
    "a majestic view",
    "an awe-inspiring scene",
    "a glorious capture",
    "a radiant masterpiece",
    "a striking scene",
    "a delightful shot",
    "a picturesque view",
    "an extraordinary capture",
    "a stunning scene",
    "a splendid panorama",
    "an artistic masterpiece",
    "a superb photograph",
    "a remarkable capture",
    "an iconic scene",
    "a vibrant depiction",
    "a magnificent display",
    "a charming image",
    "a dramatic landscape",
    "a lovely composition",
    "a stunning photograph",
    "an inspiring image",
    "a breathtaking scene",
    "an elegant picture",
    "a dazzling view",
    "a colorful composition",
    "a beautiful shot",
    "a graceful view",
    "a serene image",
    "a splendid landscape",
    "a magnificent photograph",
    "a charming scene",
    "a vibrant picture",
    "an impressive view",
    "a delightful masterpiece",
    "a stunning vista",
    "a majestic capture",
    "an artistic shot",
    "a picturesque display",
    "a magnificent scene",
    "a remarkable photograph",
    "an exquisite image",
    "a breathtaking photo",
    "a stunning capture",
    "a delightful view",
    "a striking photograph",
    "an enchanting shot",
    "a radiant image",
    "a charming photograph",
    "a serene landscape",
    "an exquisite capture",
    "a majestic scene",
]

negative_labels = (
    [
        "a poorly composed shot",
        "an unappealing photo",
        "a low-quality image",
        "a bland picture",
        "an uninspiring scene",
        "a dull snapshot",
        "a lackluster view",
        "a mediocre photograph",
        "a flat composition",
        "a drab image",
        "a forgettable shot",
        "a washed-out scene",
        "a mundane picture",
        "a colorless frame",
        "a boring display",
        "an unimpressive photograph",
        "a weak perspective",
        "an uninteresting shot",
        "a lifeless image",
        "a tedious scene",
        "a common photo",
        "a plain picture",
        "an ordinary capture",
        "a generic shot",
        "a dull landscape",
        "a lackluster photograph",
        "an unremarkable view",
        "a nondescript scene",
        "an unmemorable image",
        "a prosaic capture",
        "a lackluster shot",
        "a flat photograph",
        "an uninspired picture",
        "a bland landscape",
        "an unimpressive photo",
        "a dull frame",
        "a boring composition",
        "a drab scene",
        "a weak image",
        "a lifeless photo",
        "a mundane capture",
        "a dull shot",
        "an uninteresting picture",
        "a plain photograph",
        "a colorless image",
        "a washed-out photo",
        "a flat scene",
        "a tedious capture",
        "a forgettable picture",
        "a mediocre scene",
        "a bland shot",
        "an uninspiring photograph",
        "a nondescript picture",
        "a mundane photo",
        "a boring image",
        "a lackluster view",
        "an unmemorable shot",
        "a colorless photograph",
        "an ordinary picture",
        "a dull image",
        "a flat capture",
        "an uninspired photo",
        "a lifeless scene",
        "a lackluster shot",
        "a forgettable image",
        "a bland photograph",
        "a tedious photo",
        "a boring shot",
        "a flat picture",
        "an uninteresting scene",
        "a mundane image",
        "a plain capture",
        "a lifeless photograph",
        "a dull scene",
        "a forgettable shot",
        "a washed-out image",
        "a boring photo",
        "a lackluster scene",
        "an ordinary photograph",
        "a drab picture",
        "a weak shot",
        "a bland scene",
        "a mediocre photograph",
        "a dull photo",
        "a flat capture",
        "an uninspired scene",
        "a colorless photograph",
        "an uninteresting image",
        "a plain shot",
        "a washed-out picture",
        "a lifeless capture",
        "a mundane scene",
        "a drab photograph",
        "a weak image",
        "a forgettable photo",
        "a colorless shot",
    ]
    + ["text", "logo", "watermark"] * 5
    + [
        "low quality",
        "poor",
        "mediocre",
        "blurry",
        "noisy",
        "distorted",
        "dull",
        "unremarkable",
        "flawed",
        "unsatisfactory",
        "text",
        "occluded",
        "out of frame",
    ]
    * 3
)
