[Converter]
enable = false

[Patreon]
enable = false

[ItchIo]
enable = false

[Hagrid]
enable = false

[Phrasey]
enable = false

[Hugging]
enable = false

[MCA]
enable = false

[Torch]
num_threads = 2