[global]
background_workers = 2

[global.embedding]
model = "text-embedding-3-small"

[global.information_extractor]
model = "llama3-8b-8192"

[[global.glossaries]]
type = "git"
name = "mca_wiki"
repository = "https://github.com/Luke100000/minecraft-comes-alive.wiki.git"

[converter]
enable = false

[patreons]
enable = false

[itch]
enable = false

[minecraft]
enable = false

[phrasey]
enable = false

[hugging]
enable = false

[mca]
enable = false

[error]
enable = false

[fusion_solar]
enable = false

[horde]
enable = false

[ff_vote]
enable = false