[global]
background_workers = 2

[converter]
enable = false

[patreons]
enable = false

[itch]
enable = false

[minecraft]
enable = false

[phrasey]
enable = false

[hugging]
enable = false

[mca]
enable = false

[error]
enable = false

[fusion_solar]
enable = false

[horde]
enable = false

[ff_vote]
enable = false