[global]
background_workers = 2
asyncio_debug = false

[global.embedding]
model = "text-embedding-3-small"
dimensions = 1024

[[global.glossaries]]
type = "git"
name = "mca_wiki"
repository = "https://github.com/Luke100000/minecraft-comes-alive.wiki.git"

[converter]
enable = false

[patreons]
enable = false

[itch]
enable = false

[minecraft]
enable = false

[phrasey]
enable = false

[hugging]
enable = false

[mca]
enable = false

[error]
enable = false

[fusion_solar]
enable = false

[horde]
enable = false